name: Build Release

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Clone custom items
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
      with:
        repository: Baystation12/custom-items
        path: custom-items
    - name: Build and Publish Image to Registry
      env:
        BUILD_ARGS: -Icustom-items/inc.dm
      uses: elgohr/Publish-Docker-Github-Action@47433670daec88d900599790a6fadbf5291a835b
      with:
        name: ${{ secrets.IMAGE_NAME }}
        username: ${{ secrets.REG_USER }}
        password: ${{ secrets.REG_PASS }}
        tags: "latest"
        buildargs: BUILD_ARGS
        registry: ${{ secrets.REG_URL }}
        cache: true